=== JoelW16/XsdTutorial/RecipeBook.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.cook.co.uk/" targetNamespace="http://www.cook.co.uk/" elementFormDefault="qualified">
    <xsd:include schemaLocation="RecipeTypes.xsd"/>
    <xsd:element name="RecipeBook">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Recipe" type="RecipeStructure" minOccurs="0" maxOccurs="unbounded">
                    <xsd:annotation>
                        <xsd:documentation>Recipe</xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="RecipeStructure">
            <xsd:annotation>
                <xsd:documentation>Recipe Structue</xsd:documentation>
            </xsd:annotation>
            <xsd:sequence>
                <xsd:element name="Name" type="NaturalLanguageRecipeNameStructure">
                    <xsd:annotation>
                        <xsd:documentation>Name of recipe</xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="Serves" type="xsd:integer">
                    <xsd:annotation>
                        <xsd:documentation>Number of people it servers</xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="Ingredients">
                    <xsd:annotation>
                        <xsd:documentation>List of ingredients</xsd:documentation>
                    </xsd:annotation>
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Ingredient" type="IngredientStructure" minOccurs="1" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attributeGroup ref="ModificationGroup"/>
    </xsd:complexType>
    <xsd:complexType name="IngredientStructure">
        <xsd:annotation>
            <xsd:documentation>Ingredient details</xsd:documentation>
        </xsd:annotation>
            <xsd:sequence>
                <xsd:element name="Name" type="xsd:string"/>
                <xsd:element name="Amount" type="xsd:string"/>
                <xsd:element name="Units" type="xsd:string"/>
            </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== JoelW16/XsdTutorial/RecipeBook.xml
<?xml version="1.0" encoding="UTF-8" ?>
<RecipeBook xmlns="http://www.cook.co.uk/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cook.co.uk/ RecipeBook.xsd">
	<Recipe CreationDateTime="2022-08-19T10:30:00" ModificationDateTime="2022-08-19T10:30:00">
		<Name>Pancakes</Name>
		<Serves>4</Serves>
		<Ingredients>
			<Ingredient>
				<Name>Flour</Name>
				<Amount>125</Amount>
				<Units>g</Units>
			</Ingredient>
			<Ingredient>
				<Name>Egg</Name>
				<Amount>1</Amount>
				<Units>oz</Units>
			</Ingredient>
			<Ingredient>
				<Name>Milk</Name>
				<Amount>300</Amount>
				<Units>ml</Units>
			</Ingredient>
		</Ingredients>
	</Recipe>
</RecipeBook>
